# Meta Data for SEO

## Homepage
title = "ButterOps.Dev"
titleSeparator = "-"
titleAddition = "Promoting Social Entrepreneurship"
description = "Doks is a Hugo theme helping you build modern documentation websites that are secure, fast, and SEO-ready â€” by default."

## Open Graph + Twitter Cards
images = ["doks.png"]
twitterSite = "henkverlinde"
twitterCreator = "henkverlinde"
facebookAuthor = "verlinde.henk"
facebookPublisher = "verlinde.henk"
ogLocale = "en_US"

## JSON-LD
schemaType = "Organization"
schemaLogo = "logo-doks.png"
schemaTwitter = "https://twitter.com/henkverlinde"
schemaLinkedIn = "https://www.linkedin.com/in/henkverlinde/"
schemaGitHub = "https://github.com/h-enk"
schemaSection = "blog"

## Sitelinks Search Box
siteLinksSearchBox = false

## Chrome Browser
themeColor = "#fff"

# Images
quality = 85
bgColor = "#fff"
landscapePhotoWidths = [900, 800, 700, 600, 500]
portraitPhotoWidths = [800, 700, 600, 500]
lqipWidth = "20x"

# Footer
footer = "Powered by <a href=\"https://www.netlify.com/\">Netlify</a>, <a href=\"https://gohugo.io/\">Hugo</a>, and <a href=\"https://getdoks.org/\">Doks</a>"

# Alert
alert = false
alertText = "Released <a target=\"blank\" class=\"alert-link\" href=\"https://chrome.google.com/webstore/detail/refer-web-clipper/ijklgagbolpfgfjkclcgcepdbiopnikh?hl=en\">Refer Ext.</a> into marketplace."

# Edit Page
docsRepo = "https://github.com/h-enk/doks"
editPage = true
